/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as BookingSuccessRouteImport } from './routes/booking-success'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as PatientVoiceRouteImport } from './routes/patient.voice'
import { Route as PatientVideoRouteImport } from './routes/patient.video'
import { Route as PatientSettingsRouteImport } from './routes/patient.settings'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientDocumentsRouteImport } from './routes/patient.documents'
import { Route as PatientConsultationsRouteImport } from './routes/patient.consultations'
import { Route as PatientChatRouteImport } from './routes/patient.chat'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking-success',
  path: '/booking-success',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientVoiceRoute = PatientVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => PatientRoute,
} as any)
const PatientVideoRoute = PatientVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => PatientRoute,
} as any)
const PatientSettingsRoute = PatientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PatientRoute,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientDocumentsRoute = PatientDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PatientRoute,
} as any)
const PatientConsultationsRoute = PatientConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => PatientRoute,
} as any)
const PatientChatRoute = PatientChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => PatientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/booking-success': typeof BookingSuccessRoute
  '/patient': typeof PatientRouteWithChildren
  '/services': typeof ServicesRoute
  '/patient/chat': typeof PatientChatRoute
  '/patient/consultations': typeof PatientConsultationsRoute
  '/patient/documents': typeof PatientDocumentsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/patient/video': typeof PatientVideoRoute
  '/patient/voice': typeof PatientVoiceRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/booking-success': typeof BookingSuccessRoute
  '/services': typeof ServicesRoute
  '/patient/chat': typeof PatientChatRoute
  '/patient/consultations': typeof PatientConsultationsRoute
  '/patient/documents': typeof PatientDocumentsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/patient/video': typeof PatientVideoRoute
  '/patient/voice': typeof PatientVoiceRoute
  '/patient': typeof PatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/booking-success': typeof BookingSuccessRoute
  '/patient': typeof PatientRouteWithChildren
  '/services': typeof ServicesRoute
  '/patient/chat': typeof PatientChatRoute
  '/patient/consultations': typeof PatientConsultationsRoute
  '/patient/documents': typeof PatientDocumentsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/patient/video': typeof PatientVideoRoute
  '/patient/voice': typeof PatientVoiceRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/booking-success'
    | '/patient'
    | '/services'
    | '/patient/chat'
    | '/patient/consultations'
    | '/patient/documents'
    | '/patient/profile'
    | '/patient/settings'
    | '/patient/video'
    | '/patient/voice'
    | '/patient/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/booking-success'
    | '/services'
    | '/patient/chat'
    | '/patient/consultations'
    | '/patient/documents'
    | '/patient/profile'
    | '/patient/settings'
    | '/patient/video'
    | '/patient/voice'
    | '/patient'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/booking-success'
    | '/patient'
    | '/services'
    | '/patient/chat'
    | '/patient/consultations'
    | '/patient/documents'
    | '/patient/profile'
    | '/patient/settings'
    | '/patient/video'
    | '/patient/voice'
    | '/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  PatientRoute: typeof PatientRouteWithChildren
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-success': {
      id: '/booking-success'
      path: '/booking-success'
      fullPath: '/booking-success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/voice': {
      id: '/patient/voice'
      path: '/voice'
      fullPath: '/patient/voice'
      preLoaderRoute: typeof PatientVoiceRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/video': {
      id: '/patient/video'
      path: '/video'
      fullPath: '/patient/video'
      preLoaderRoute: typeof PatientVideoRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/settings': {
      id: '/patient/settings'
      path: '/settings'
      fullPath: '/patient/settings'
      preLoaderRoute: typeof PatientSettingsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/documents': {
      id: '/patient/documents'
      path: '/documents'
      fullPath: '/patient/documents'
      preLoaderRoute: typeof PatientDocumentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/consultations': {
      id: '/patient/consultations'
      path: '/consultations'
      fullPath: '/patient/consultations'
      preLoaderRoute: typeof PatientConsultationsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/chat': {
      id: '/patient/chat'
      path: '/chat'
      fullPath: '/patient/chat'
      preLoaderRoute: typeof PatientChatRouteImport
      parentRoute: typeof PatientRoute
    }
  }
}

interface PatientRouteChildren {
  PatientChatRoute: typeof PatientChatRoute
  PatientConsultationsRoute: typeof PatientConsultationsRoute
  PatientDocumentsRoute: typeof PatientDocumentsRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientSettingsRoute: typeof PatientSettingsRoute
  PatientVideoRoute: typeof PatientVideoRoute
  PatientVoiceRoute: typeof PatientVoiceRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientChatRoute: PatientChatRoute,
  PatientConsultationsRoute: PatientConsultationsRoute,
  PatientDocumentsRoute: PatientDocumentsRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientSettingsRoute: PatientSettingsRoute,
  PatientVideoRoute: PatientVideoRoute,
  PatientVoiceRoute: PatientVoiceRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  PatientRoute: PatientRouteWithChildren,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
